spring:
  profiles:
    active:
            - ES
            - dog
            - prod

ssd:
  username: YMLUser
  password: YMLPassword
  jdbcurl: YMLURL

---
ssd:
  username: YmlProdUser
  password: YmlProdPassword
  jdbcurl: YmlProdURL
